### ISSUE TITLE
Readme example throwing error

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [yash1994/dframcy#3]
Hi, In your read me file examples; # Token-based Matching part is not working and throwing below error

ValueError: [E171] Matcher.add received invalid 'on_match' callback argument: expected callable or None, but got: <class 'list'>

**Comment by yash1994** [comment]
Hi, there were few changes in API with spacy v3. Changes were left to be reflected in the readme. Checked all examples in the readme and made necessary changes. Thanks for pointing it out.
